version: '3.8'

services:
  postgres_db:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data2:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  postgres_data2:
